version: '3.8'

services:
  prometheus:
    container_name: quarkus-metrics-prometheus
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: quarkus-metrics-grafana
    image: grafana/grafana:7.3.7
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: quarkus-metrics-network